INSTALLED_APPS = [
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    "rest_framework",
    "corsheaders",
    "djoser",
    "split_settings",
    "django_filters",
    "drf_extra_fields",
    "apps.administration.apps.AdministrationConfig",
    "apps.cloud.apps.CloudConfig",
    "drf_spectacular",
]
