# Generated by Django 5.1 on 2024-08-27 16:19

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("cloud", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="file",
            name="type",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
