# Generated by Django 5.1 on 2024-08-28 09:21

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("cloud", "0002_file_type"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="file",
            options={"verbose_name": "Файл", "verbose_name_plural": "Файлы"},
        ),
    ]
