# Generated by Django 5.1 on 2024-08-27 09:53

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("administration", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="full_name",
            field=models.CharField(
                blank=True, max_length=300, verbose_name="Полное имя"
            ),
        ),
    ]
